#!/bin/bash
echo "=== AWS Laravel環境 ==="
echo ""
echo "=== アクセス方法 ==="
echo "ALB経由アクセス: http://$(terraform output -raw alb_dns_name)"
echo "EC2直接アクセス: http://$(terraform output -raw instance_public_ip)"
echo ""
echo "=== SSHアクセス（作成した秘密鍵を使用）==="
echo "ssh -i keys/terraform-key ec2-user@$(terraform output -raw instance_public_ip)"
echo ""
echo "=== S3バケット情報 ==="
echo "バケット名: $(terraform output -raw s3_bucket_name)"
echo "バケットARN: $(terraform output -raw s3_bucket_arn)"
echo ""
