---
- name: Laravel環境構築
  hosts: web_servers
  become: yes
  vars:
    php_version: "8.2"
    laravel_app_name: "laravel-app"
    laravel_app_path: "/var/www/{{ laravel_app_name }}"
    nginx_domain: "{{ ansible_default_ipv4.address }}"
    # s3_bucket_nameはインベントリから取得

  roles:
    - php
    - laravel
    - nginx

  handlers:
    - name: restart nginx
      # トラブルシューティング用: nginxは再起動せずに停止
      service:
        name: nginx
        state: stopped
        enabled: no

    - name: restart php-fpm
      service:
        name: php-fpm
        state: restarted
        enabled: yes
